#!/usr/bin/with-contenv bash
set -euo pipefail

CONFIG="/data/options.json"

# Fixed values
APP_ID=232330
SERVER_DIR="/share/css_server"
PORT=27015
TV_PORT=27020

UPDATE_ON_BOOT="$(jq -r '.update_on_boot' "$CONFIG")"
SKIP_VERIFY="$(jq -r '.skip_steam_verify' "$CONFIG")"
ENABLE_DEBUG="$(jq -r '.enable_debug' "$CONFIG")"

HOSTNAME="$(jq -r '.hostname' "$CONFIG")"
MAXPLAYERS="$(jq -r '.maxplayers' "$CONFIG")"
MAP="$(jq -r '.map' "$CONFIG")"
TICKRATE="$(jq -r '.tickrate' "$CONFIG")"
GSLT="$(jq -r '.gslt // empty' "$CONFIG")"

WRITE_CFG="$(jq -r '.write_cfg_files' "$CONFIG")"
SV_LAN="$(jq -r '.sv_lan' "$CONFIG")"
RCON_PASSWORD="$(jq -r '.rcon_password' "$CONFIG")"
SV_PASSWORD="$(jq -r '.sv_password // empty' "$CONFIG")"

LOG_ON="$(jq -r '.log_on' "$CONFIG")"
LOG_VERBOSE="$(jq -r '.log_verbose' "$CONFIG")"
LOGADDRESS="$(jq -r '.logaddress // empty' "$CONFIG")"

ENABLE_SOURCETV="$(jq -r '.enable_sourcetv' "$CONFIG")"
SOURCETV_NAME="$(jq -r '.sourcetv_name // empty' "$CONFIG")"

mkdir -p "$SERVER_DIR"

# SteamCMD update (non-fatal)
if [[ "$UPDATE_ON_BOOT" == "true" ]]; then
  if getent hosts steamcdn-a.akamaihd.net >/dev/null 2>&1; then
    echo "[INFO] Updating Counter-Strike: Source server via SteamCMD..."

    STEAM_UPDATE_CMD="+app_update $APP_ID"
    [[ "$SKIP_VERIFY" != "true" ]] && STEAM_UPDATE_CMD="$STEAM_UPDATE_CMD validate"

    set +e
    /steamcmd/steamcmd.sh \
      +@ShutdownOnFailedCommand 1 \
      +@NoPromptForPassword 1 \
      +force_install_dir "$SERVER_DIR" \
      +login anonymous \
      $STEAM_UPDATE_CMD \
      +quit
    set -e
  else
    echo "[WARN] SteamCMD network check failed, skipping update."
  fi
fi

# Steam environment (ABI safe)
export STEAMCMDDIR="/steamcmd"
export HOME="/root"
unset LD_LIBRARY_PATH || true

# Steam runtime symlinks
mkdir -p /root/.steam/sdk32 /root/.steam/sdk64

[[ -f /steamcmd/linux32/steamclient.so ]] && ln -sf /steamcmd/linux32/steamclient.so /root/.steam/sdk32/steamclient.so
[[ -f /steamcmd/linux64/steamclient.so ]] && ln -sf /steamcmd/linux64/steamclient.so /root/.steam/sdk64/steamclient.so

[[ -f /steamcmd/linux32/steamservice.so ]] && ln -sf /steamcmd/linux32/steamservice.so /root/.steam/sdk32/steamservice.so
[[ -f /steamcmd/linux64/steamservice.so ]] && ln -sf /steamcmd/linux64/steamservice.so /root/.steam/sdk64/steamservice.so

# Persistent RCON password handling
RCON_STORE="/data/rcon_password.txt"
if [[ "$RCON_PASSWORD" == "CHANGE_ME" || -z "$RCON_PASSWORD" || "$RCON_PASSWORD" == "null" ]]; then
  if [[ -s "$RCON_STORE" ]]; then
    RCON_PASSWORD="$(cat "$RCON_STORE")"
  else
    RCON_PASSWORD="$(openssl rand -base64 32 | tr -d '\n' | tr '/+' 'Aa' | cut -c1-32)"
    echo "$RCON_PASSWORD" > "$RCON_STORE"
    chmod 600 "$RCON_STORE" || true
    echo "[WARN] RCON password was CHANGE_ME. A secure password was generated and stored."
  fi
fi

# Config generation
CFG_DIR="$SERVER_DIR/cstrike/cfg"
mkdir -p "$CFG_DIR"

SERVER_CFG="$CFG_DIR/server.cfg"
AUTOEXEC_CFG="$CFG_DIR/autoexec.cfg"

if [[ "$WRITE_CFG" == "true" ]]; then
  cat > "$SERVER_CFG" <<EOF
// Auto-generated by Home Assistant Add-on (server.cfg)

hostname "${HOSTNAME}"
sv_lan ${SV_LAN}

rcon_password "${RCON_PASSWORD}"
sv_password "${SV_PASSWORD}"

sv_cheats 0
sv_pausable 0
sv_alltalk 0

log on
sv_logecho ${LOG_VERBOSE}
sv_logfile ${LOG_VERBOSE}
sv_log_onefile 0
EOF

  [[ "$LOG_ON" != "true" ]] && echo "log off" >> "$SERVER_CFG"
  [[ -n "$LOGADDRESS" && "$LOGADDRESS" != "null" ]] && echo "logaddress_add ${LOGADDRESS}" >> "$SERVER_CFG"

  if [[ "$ENABLE_SOURCETV" == "true" ]]; then
    cat >> "$SERVER_CFG" <<EOF

// SourceTV
tv_enable 1
tv_port ${TV_PORT}
tv_name "${SOURCETV_NAME}"
tv_autorecord 0
tv_maxclients 4
tv_allow_camera_man 0
EOF
  fi

  cat > "$AUTOEXEC_CFG" <<EOF
// Auto-generated by Home Assistant Add-on (autoexec.cfg)

echo "=============================="
echo " HAOS CS:S Dedicated starting "
echo "=============================="
EOF
fi

cd "$SERVER_DIR"

EXTRA_ARGS=""
[[ "$ENABLE_DEBUG" == "true" ]] && EXTRA_ARGS="$EXTRA_ARGS -debug"
[[ -n "$GSLT" && "$GSLT" != "null" ]] && EXTRA_ARGS="$EXTRA_ARGS +sv_setsteamaccount $GSLT"

echo "[INFO] Starting Counter-Strike: Source Dedicated Server"

exec ./srcds_run \
  -game cstrike \
  -console \
  -port "$PORT" \
  -tickrate "$TICKRATE" \
  +maxplayers "$MAXPLAYERS" \
  +map "$MAP" \
  +hostname "$HOSTNAME" \
  $EXTRA_ARGS
